name: Despliegue de Spring Boot con Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Java y Docker
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Construir y empaquetar la aplicación Spring Boot con Docker
      run: |
        chmod +x mvnw
        ./mvnw clean install -DskipTests
    - name: Login to docker hub
      run:
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run:
        docker build -t 643434343434/make_pizza .
    - name: docker push to docker hub
      run:
        docker push 643434343434/make_pizza:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull 643434343434/make_pizza:latest
      - name: delete old container
        run: docker rm -f make_pizza_container
      - name: Run docker container
        run: docker run -d -p 9191:9191 --name make_pizza_container 643434343434/make_pizza:latest
